title: Priya Dhawka
url: "https://dhawkap.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Last updated: 12/07/2024"


sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Publications"
   link: "publications"
 - name: "CV"
   link: "Priya-Dhawka-CV.pdf"
 # - name: "Contact"
 #   link: "contact" 
