title: Priya Dhawka
url: "https://dhawkap.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no


sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Publications"
   link: "publications"
 - name: "CV"
   link: "Priya-Dhawka-CV-2023.pdf"
 - name: "Contact"
   link: "contact" 
